"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-10-08 14:11:24.203834
"""
from alembic import op
import sqlalchemy as sa
import app.models


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('segmento', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=32), nullable=True),
    sa.Column('fuso', sa.String(length=64), nullable=False),
    sa.Column('permite_ia_externa', sa.Boolean(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('seq_ordem', sa.Integer(), nullable=False),
    sa.Column('criada_em', app.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=80), nullable=False),
    sa.Column('unidade_medida', sa.String(length=30), nullable=False),
    sa.Column('caracteristicas', sa.JSON(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome')
    )
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_materiais_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('caracteristicas', sa.JSON(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao_operacao', sa.Text(), nullable=False),
    sa.Column('objetivo', sa.Text(), nullable=False),
    sa.Column('principais_problemas', sa.Text(), nullable=False),
    sa.Column('informacoes_disponiveis', sa.Text(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criada_em', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome')
    )
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_unidades_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('falhas_login', sa.Integer(), nullable=False),
    sa.Column('bloqueado_ate', app.models.UTCDateTime(), nullable=True),
    sa.Column('token_versao', sa.Integer(), nullable=False),
    sa.Column('ultimo_login', app.models.UTCDateTime(), nullable=True),
    sa.Column('criado_em', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_empresa_id'), ['empresa_id'], unique=False)

    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('entidade', sa.String(length=60), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('depois', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('em', app.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_acao'), ['acao'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_em'), ['em'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_entidade'), ['entidade'], unique=False)

    op.create_table('diagnostico_perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('grupo', sa.String(length=60), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=60), nullable=False),
    sa.Column('criada_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('respondida_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('respondida_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['respondida_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnostico_perguntas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diagnostico_perguntas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_diagnostico_perguntas_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('funcao', sa.String(length=120), nullable=False),
    sa.Column('equipe', sa.String(length=120), nullable=False),
    sa.Column('habilitacoes', sa.JSON(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pessoas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pessoas_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('recomendacoes_ia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=40), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('conteudo', sa.JSON(), nullable=False),
    sa.Column('evidencias', sa.JSON(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('provedor', sa.String(length=80), nullable=False),
    sa.Column('alvo_tipo', sa.String(length=30), nullable=True),
    sa.Column('alvo_id', sa.Integer(), nullable=True),
    sa.Column('criada_por', sa.Integer(), nullable=True),
    sa.Column('criada_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('decidida_por', sa.Integer(), nullable=True),
    sa.Column('decidida_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('decisao_obs', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['criada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['decidida_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('recomendacoes_ia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recomendacoes_ia_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recomendacoes_ia_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('recursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('processos_relacionados', sa.JSON(), nullable=False),
    sa.Column('capacidade', sa.Float(), nullable=True),
    sa.Column('capacidade_unidade', sa.String(length=40), nullable=False),
    sa.Column('equipes_habilitadas', sa.JSON(), nullable=False),
    sa.Column('local_posto', sa.String(length=200), nullable=False),
    sa.Column('horas_disponiveis_dia', sa.Float(), nullable=False),
    sa.Column('ultima_manutencao', sa.Date(), nullable=True),
    sa.Column('proxima_manutencao', sa.Date(), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'nome')
    )
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recursos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_recursos_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('usuario_unidades',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'unidade_id')
    )
    op.create_table('parametros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('escopo_tipo', sa.String(length=20), nullable=False),
    sa.Column('escopo_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=80), nullable=False),
    sa.Column('valor_num', sa.Float(), nullable=True),
    sa.Column('valor_texto', sa.String(length=300), nullable=True),
    sa.Column('unidade', sa.String(length=30), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('status_validacao', sa.String(length=20), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('vigente', sa.Boolean(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('recomendacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('validado_por', sa.Integer(), nullable=True),
    sa.Column('validado_em', app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['recomendacao_id'], ['recomendacoes_ia.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('parametros', schema=None) as batch_op:
        batch_op.create_index('ix_param_escopo', ['empresa_id', 'escopo_tipo', 'escopo_id', 'nome'], unique=False)
        batch_op.create_index(batch_op.f('ix_parametros_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_parametros_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('processos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=36), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('macroprocesso', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('responsavel_id', sa.Integer(), nullable=True),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('recomendacao_id', sa.Integer(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('publicado_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('publicado_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['publicado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['recomendacao_id'], ['recomendacoes_ia.id'], ),
    sa.ForeignKeyConstraint(['responsavel_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'codigo', 'versao')
    )
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_processos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_processos_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('entradas', sa.JSON(), nullable=False),
    sa.Column('saidas', sa.JSON(), nullable=False),
    sa.Column('opcional', sa.Boolean(), nullable=False),
    sa.Column('condicao', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('etapas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_etapas_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_etapas_processo_id'), ['processo_id'], unique=False)

    op.create_table('ordens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=20), nullable=False),
    sa.Column('cliente', sa.String(length=200), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=300), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('prazo', sa.Date(), nullable=True),
    sa.Column('processo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('tempo_estimado_min', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('cancelamento_motivo', sa.Text(), nullable=False),
    sa.Column('criada_por', sa.Integer(), nullable=True),
    sa.Column('criada_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('liberada_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('iniciada_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('concluida_em', app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['processo_id'], ['processos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'numero')
    )
    with op.batch_alter_table('ordens', schema=None) as batch_op:
        batch_op.create_index('ix_ordem_status', ['empresa_id', 'unidade_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordens_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('operacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('formula_tipo', sa.String(length=20), nullable=False),
    sa.Column('unidade_medida', sa.String(length=30), nullable=False),
    sa.Column('recurso_padrao_id', sa.Integer(), nullable=True),
    sa.Column('dados_medidos', sa.JSON(), nullable=False),
    sa.Column('campos_extras', sa.JSON(), nullable=False),
    sa.Column('ergonomia', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas.id'], ),
    sa.ForeignKeyConstraint(['recurso_padrao_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('operacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_operacoes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_operacoes_etapa_id'), ['etapa_id'], unique=False)

    op.create_table('ordem_operacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=True),
    sa.Column('sequencia', sa.Integer(), nullable=False),
    sa.Column('etapa_nome', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('qtd_planejada', sa.Float(), nullable=False),
    sa.Column('formula_tipo', sa.String(length=20), nullable=False),
    sa.Column('tempo_prep_est_min', sa.Float(), nullable=True),
    sa.Column('tempo_exec_est_min', sa.Float(), nullable=True),
    sa.Column('fonte_estimativa', sa.String(length=20), nullable=False),
    sa.Column('amostras', sa.Integer(), nullable=False),
    sa.Column('opcional', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('iniciada_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('concluida_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('concluida_por', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['concluida_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ordem_operacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ordem_operacoes_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ordem_operacoes_ordem_id'), ['ordem_id'], unique=False)

    op.create_table('apontamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('ordem_operacao_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('inicio', app.models.UTCDateTime(), nullable=False),
    sa.Column('fim', app.models.UTCDateTime(), nullable=True),
    sa.Column('quantidade_boa', sa.Float(), nullable=False),
    sa.Column('quantidade_refugo', sa.Float(), nullable=False),
    sa.Column('dados_extras', sa.JSON(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('registrado_por', sa.Integer(), nullable=False),
    sa.Column('registrado_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('decidido_por', sa.Integer(), nullable=True),
    sa.Column('decidido_em', app.models.UTCDateTime(), nullable=True),
    sa.Column('anulado', sa.Boolean(), nullable=False),
    sa.Column('anulado_motivo', sa.Text(), nullable=False),
    sa.Column('anulado_por', sa.Integer(), nullable=True),
    sa.Column('anulado_em', app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['anulado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['decidido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens.id'], ),
    sa.ForeignKeyConstraint(['ordem_operacao_id'], ['ordem_operacoes.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['registrado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apontamentos', schema=None) as batch_op:
        batch_op.create_index('ix_apont_inicio', ['empresa_id', 'unidade_id', 'inicio'], unique=False)
        batch_op.create_index('ix_apont_ordem', ['empresa_id', 'ordem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apontamentos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_apontamentos_ordem_operacao_id'), ['ordem_operacao_id'], unique=False)

    op.create_table('ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=True),
    sa.Column('ordem_operacao_id', sa.Integer(), nullable=True),
    sa.Column('recurso_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('causa', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('impacto', sa.String(length=300), nullable=False),
    sa.Column('inicio', app.models.UTCDateTime(), nullable=False),
    sa.Column('fim', app.models.UTCDateTime(), nullable=True),
    sa.Column('registrada_por', sa.Integer(), nullable=False),
    sa.Column('registrada_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('anulada', sa.Boolean(), nullable=False),
    sa.Column('anulada_motivo', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens.id'], ),
    sa.ForeignKeyConstraint(['ordem_operacao_id'], ['ordem_operacoes.id'], ),
    sa.ForeignKeyConstraint(['recurso_id'], ['recursos.id'], ),
    sa.ForeignKeyConstraint(['registrada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ocorrencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ocorrencias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocorrencias_ordem_id'), ['ordem_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ocorrencias_unidade_id'), ['unidade_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ocorrencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ocorrencias_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencias_ordem_id'))
        batch_op.drop_index(batch_op.f('ix_ocorrencias_empresa_id'))

    op.drop_table('ocorrencias')
    with op.batch_alter_table('apontamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_apontamentos_ordem_operacao_id'))
        batch_op.drop_index(batch_op.f('ix_apontamentos_empresa_id'))
        batch_op.drop_index('ix_apont_ordem')
        batch_op.drop_index('ix_apont_inicio')

    op.drop_table('apontamentos')
    with op.batch_alter_table('ordem_operacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordem_operacoes_ordem_id'))
        batch_op.drop_index(batch_op.f('ix_ordem_operacoes_empresa_id'))

    op.drop_table('ordem_operacoes')
    with op.batch_alter_table('operacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_operacoes_etapa_id'))
        batch_op.drop_index(batch_op.f('ix_operacoes_empresa_id'))

    op.drop_table('operacoes')
    with op.batch_alter_table('ordens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ordens_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_ordens_empresa_id'))
        batch_op.drop_index('ix_ordem_status')

    op.drop_table('ordens')
    with op.batch_alter_table('etapas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_etapas_processo_id'))
        batch_op.drop_index(batch_op.f('ix_etapas_empresa_id'))

    op.drop_table('etapas')
    with op.batch_alter_table('processos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_processos_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_processos_empresa_id'))

    op.drop_table('processos')
    with op.batch_alter_table('parametros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parametros_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_parametros_empresa_id'))
        batch_op.drop_index('ix_param_escopo')

    op.drop_table('parametros')
    op.drop_table('usuario_unidades')
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recursos_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_recursos_empresa_id'))

    op.drop_table('recursos')
    with op.batch_alter_table('recomendacoes_ia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recomendacoes_ia_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_recomendacoes_ia_empresa_id'))

    op.drop_table('recomendacoes_ia')
    with op.batch_alter_table('pessoas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pessoas_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_pessoas_empresa_id'))

    op.drop_table('pessoas')
    with op.batch_alter_table('diagnostico_perguntas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diagnostico_perguntas_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_diagnostico_perguntas_empresa_id'))

    op.drop_table('diagnostico_perguntas')
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_entidade'))
        batch_op.drop_index(batch_op.f('ix_auditoria_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_em'))
        batch_op.drop_index(batch_op.f('ix_auditoria_acao'))

    op.drop_table('auditoria')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_empresa_id'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('unidades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_unidades_empresa_id'))

    op.drop_table('unidades')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_empresa_id'))

    op.drop_table('produtos')
    with op.batch_alter_table('materiais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_materiais_empresa_id'))

    op.drop_table('materiais')
    op.drop_table('empresas')
    # ### end Alembic commands ###
