"""gemeo digital

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-08 14:30:10.925101
"""
from alembic import op
import sqlalchemy as sa
import app.models


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espacos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('comprimento_m', sa.Float(), nullable=True),
    sa.Column('largura_m', sa.Float(), nullable=True),
    sa.Column('pe_direito_m', sa.Float(), nullable=True),
    sa.Column('piso', sa.String(length=80), nullable=False),
    sa.Column('temperatura_c', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'nome')
    )
    with op.batch_alter_table('espacos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_espacos_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_espacos_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('distancias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('origem_id', sa.Integer(), nullable=False),
    sa.Column('destino_id', sa.Integer(), nullable=False),
    sa.Column('metros', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['destino_id'], ['espacos.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['origem_id'], ['espacos.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('origem_id', 'destino_id')
    )
    with op.batch_alter_table('distancias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_distancias_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_distancias_unidade_id'), ['unidade_id'], unique=False)

    op.create_table('modelos_tempo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('operacao_id', sa.Integer(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('elementos', sa.JSON(), nullable=False),
    sa.Column('fator_ambiente', sa.Float(), nullable=False),
    sa.Column('premissas', sa.JSON(), nullable=False),
    sa.Column('dados_faltantes', sa.JSON(), nullable=False),
    sa.Column('padrao_apontamento', sa.JSON(), nullable=False),
    sa.Column('confianca', sa.String(length=10), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('provedor', sa.String(length=80), nullable=False),
    sa.Column('status_validacao', sa.String(length=20), nullable=False),
    sa.Column('contexto', sa.JSON(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', app.models.UTCDateTime(), nullable=False),
    sa.Column('validado_por', sa.Integer(), nullable=True),
    sa.Column('validado_em', app.models.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['criado_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['operacao_id'], ['operacoes.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('modelos_tempo', schema=None) as batch_op:
        batch_op.create_index('ix_modelo_op', ['empresa_id', 'operacao_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelos_tempo_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_modelos_tempo_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('operacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('funcao_requerida', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('num_pessoas', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('espaco_origem_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('espaco_destino_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('distancia_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('item_peso_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('item_comprimento_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('item_largura_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('item_altura_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('inicio_marco', sa.String(length=300), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('fim_marco', sa.String(length=300), nullable=False, server_default=''))
        batch_op.create_foreign_key('fk_operacoes_espaco_destino', 'espacos', ['espaco_destino_id'], ['id'])
        batch_op.create_foreign_key('fk_operacoes_espaco_origem', 'espacos', ['espaco_origem_id'], ['id'])

    with op.batch_alter_table('ordem_operacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalhe_estimativa', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('estimativa_validada', sa.Boolean(), nullable=False, server_default=sa.true()))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peso_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comprimento_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('largura_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('altura_m', sa.Float(), nullable=True))

    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('espaco_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_recursos_espaco', 'espacos', ['espaco_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recursos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recursos_espaco', type_='foreignkey')
        batch_op.drop_column('espaco_id')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('altura_m')
        batch_op.drop_column('largura_m')
        batch_op.drop_column('comprimento_m')
        batch_op.drop_column('peso_kg')

    with op.batch_alter_table('ordem_operacoes', schema=None) as batch_op:
        batch_op.drop_column('estimativa_validada')
        batch_op.drop_column('detalhe_estimativa')

    with op.batch_alter_table('operacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_operacoes_espaco_destino', type_='foreignkey')
        batch_op.drop_constraint('fk_operacoes_espaco_origem', type_='foreignkey')
        batch_op.drop_column('fim_marco')
        batch_op.drop_column('inicio_marco')
        batch_op.drop_column('item_altura_m')
        batch_op.drop_column('item_largura_m')
        batch_op.drop_column('item_comprimento_m')
        batch_op.drop_column('item_peso_kg')
        batch_op.drop_column('distancia_m')
        batch_op.drop_column('espaco_destino_id')
        batch_op.drop_column('espaco_origem_id')
        batch_op.drop_column('num_pessoas')
        batch_op.drop_column('funcao_requerida')

    with op.batch_alter_table('modelos_tempo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modelos_tempo_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_modelos_tempo_empresa_id'))
        batch_op.drop_index('ix_modelo_op')

    op.drop_table('modelos_tempo')
    with op.batch_alter_table('distancias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_distancias_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_distancias_empresa_id'))

    op.drop_table('distancias')
    with op.batch_alter_table('espacos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_espacos_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_espacos_empresa_id'))

    op.drop_table('espacos')
    # ### end Alembic commands ###
