"""fatores humanos

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-08 14:46:38.236851
"""
from alembic import op
import sqlalchemy as sa
import app.models


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfis_mao_de_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('sexo', sa.String(length=20), nullable=False),
    sa.Column('estatura_cm', sa.Float(), nullable=True),
    sa.Column('peso_corporal_kg', sa.Float(), nullable=True),
    sa.Column('altura_cotovelo_cm', sa.Float(), nullable=True),
    sa.Column('faixa_etaria', sa.String(length=20), nullable=False),
    sa.Column('experiencia', sa.String(length=20), nullable=False),
    sa.Column('ritmo_pct', sa.Float(), nullable=False),
    sa.Column('limite_energetico_kcal_min', sa.Float(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'nome')
    )
    with op.batch_alter_table('perfis_mao_de_obra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perfis_mao_de_obra_empresa_id'), ['empresa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_perfis_mao_de_obra_unidade_id'), ['unidade_id'], unique=False)

    with op.batch_alter_table('espacos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('umidade_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ruido_db', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('iluminancia_lux', sa.Float(), nullable=True))

    with op.batch_alter_table('modelos_tempo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ritmo_pct', sa.Float(), nullable=False, server_default='100'))
        batch_op.add_column(sa.Column('tolerancias', sa.JSON(), nullable=False, server_default='[]'))

    with op.batch_alter_table('operacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_movimento', sa.String(length=40), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('postura_trabalho', sa.String(length=20), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('altura_trabalho_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('gasto_energetico_kcal_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('levantamento', sa.JSON(), nullable=True))
        batch_op.create_foreign_key('fk_operacoes_perfil', 'perfis_mao_de_obra', ['perfil_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operacoes', schema=None) as batch_op:
        batch_op.drop_constraint('fk_operacoes_perfil', type_='foreignkey')
        batch_op.drop_column('levantamento')
        batch_op.drop_column('gasto_energetico_kcal_min')
        batch_op.drop_column('altura_trabalho_m')
        batch_op.drop_column('postura_trabalho')
        batch_op.drop_column('tipo_movimento')
        batch_op.drop_column('perfil_id')

    with op.batch_alter_table('modelos_tempo', schema=None) as batch_op:
        batch_op.drop_column('tolerancias')
        batch_op.drop_column('ritmo_pct')

    with op.batch_alter_table('espacos', schema=None) as batch_op:
        batch_op.drop_column('iluminancia_lux')
        batch_op.drop_column('ruido_db')
        batch_op.drop_column('umidade_pct')

    with op.batch_alter_table('perfis_mao_de_obra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perfis_mao_de_obra_unidade_id'))
        batch_op.drop_index(batch_op.f('ix_perfis_mao_de_obra_empresa_id'))

    op.drop_table('perfis_mao_de_obra')
    # ### end Alembic commands ###
